<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class T_ProjectSeeder extends Seeder
{
    public function run(): void
    {
        Project::create([
            'client_id' => '1',
            'project_num' => '100102-C01-0001',
            'project_name' => '【CUS.】寄付金管理システム',
            'sales_stage_id' => '1',
            'accounting_type_id' => '1',
            'project_type_id' => '1',
            'company_id' => '1',
            'department_id' => '1',
            'division_id' => '1',
            'project_memo' => 'テスト',
            'user_id' => '1',
            'distribution_type_id' => '1',
            'client_budget_year' => '2024',
            'accounting_start_date' => '2024-11-01',
            'accounting_end_date' => '2025-10-01',
            'accounting_period_id_1' => '4',
            'revenue_distribution_set1_0' => '50000',
            'revenue_distribution_set1_1' => '50000',
            'revenue_distribution_set1_2' => '50000',
            'revenue_distribution_set1_3' => '50000',
            'revenue_distribution_set1_4' => '50000',
            'revenue_distribution_set1_5' => '50000',
            'revenue_distribution_set1_6' => '50000',
            'revenue_distribution_set1_7' => '50000',
            'revenue_distribution_set1_8' => '50000',
            'revenue_distribution_set1_9' => '50000',
            'revenue_distribution_set1_10' => '50000',
            'revenue_distribution_set1_11' => '50000',
            'accounting_period_id_2' => '5',
            'revenue_distribution_set2_0' => '0',
            'revenue_distribution_set2_1' => '0',
            'revenue_distribution_set2_2' => '0',
            'revenue_distribution_set2_3' => '0',
            'revenue_distribution_set2_4' => '0',
            'revenue_distribution_set2_5' => '0',
            'revenue_distribution_set2_6' => '0',
            'revenue_distribution_set2_7' => '0',
            'revenue_distribution_set2_8' => '0',
            'revenue_distribution_set2_9' => '0',
            'revenue_distribution_set2_10' => '0',
            'revenue_distribution_set2_11' => '0'
        ]);
        Project::create([
            'client_id' => '1',
            'project_num' => '100102-C01-0002',
            'project_name' => '教務システム',
            'sales_stage_id' => '1',
            'accounting_type_id' => '1',
            'project_type_id' => '1',
            'company_id' => '1',
            'department_id' => '1',
            'division_id' => '1',
            'project_memo' => 'テスト',
            'user_id' => '1',
            'distribution_type_id' => '1',
            'client_budget_year' => '2024',
            'accounting_start_date' => '2024-11-01',
            'accounting_end_date' => '2025-10-01',
            'accounting_period_id_1' => '4',
            'revenue_distribution_set1_0' => '10000',
            'revenue_distribution_set1_1' => '10000',
            'revenue_distribution_set1_2' => '10000',
            'revenue_distribution_set1_3' => '10000',
            'revenue_distribution_set1_4' => '10000',
            'revenue_distribution_set1_5' => '10000',
            'revenue_distribution_set1_6' => '10000',
            'revenue_distribution_set1_7' => '10000',
            'revenue_distribution_set1_8' => '10000',
            'revenue_distribution_set1_9' => '10000',
            'revenue_distribution_set1_10' => '10000',
            'revenue_distribution_set1_11' => '10000',
            'accounting_period_id_2' => '5',
            'revenue_distribution_set2_0' => '400000',
            'revenue_distribution_set2_1' => '0',
            'revenue_distribution_set2_2' => '0',
            'revenue_distribution_set2_3' => '0',
            'revenue_distribution_set2_4' => '0',
            'revenue_distribution_set2_5' => '0',
            'revenue_distribution_set2_6' => '0',
            'revenue_distribution_set2_7' => '0',
            'revenue_distribution_set2_8' => '0',
            'revenue_distribution_set2_9' => '0',
            'revenue_distribution_set2_10' => '0',
            'revenue_distribution_set2_11' => '0'
        ]);
        Project::create([
            'client_id' => '1',
            'project_num' => '100102-C01-0003',
            'project_name' => '【追加】入試システム',
            'sales_stage_id' => '1',
            'accounting_type_id' => '1',
            'project_type_id' => '1',
            'company_id' => '1',
            'department_id' => '1',
            'division_id' => '1',
            'project_memo' => 'テスト',
            'user_id' => '1',
            'distribution_type_id' => '1',
            'client_budget_year' => '2024',
            'accounting_start_date' => '2024-11-01',
            'accounting_end_date' => '2025-10-01',
            'accounting_period_id_1' => '4',
            'revenue_distribution_set1_0' => '0',
            'revenue_distribution_set1_1' => '0',
            'revenue_distribution_set1_2' => '0',
            'revenue_distribution_set1_3' => '0',
            'revenue_distribution_set1_4' => '0',
            'revenue_distribution_set1_5' => '0',
            'revenue_distribution_set1_6' => '0',
            'revenue_distribution_set1_7' => '0',
            'revenue_distribution_set1_8' => '0',
            'revenue_distribution_set1_9' => '0',
            'revenue_distribution_set1_10' => '0',
            'revenue_distribution_set1_11' => '0',
            'accounting_period_id_2' => '5',
            'revenue_distribution_set2_0' => '10000',
            'revenue_distribution_set2_1' => '10000',
            'revenue_distribution_set2_2' => '10000',
            'revenue_distribution_set2_3' => '10000',
            'revenue_distribution_set2_4' => '10000',
            'revenue_distribution_set2_5' => '10000',
            'revenue_distribution_set2_6' => '10000',
            'revenue_distribution_set2_7' => '10000',
            'revenue_distribution_set2_8' => '10000',
            'revenue_distribution_set2_9' => '10000',
            'revenue_distribution_set2_10' => '10000',
            'revenue_distribution_set2_11' => '10000'
        ]);
    }
}
